- name: Bring up docker containers
  hosts: localhost
  vars:
    inventory:
      - name: master
        expose: 22
        ports: "2200:22"
      # - name: worker1
      #   expose: 22
      #   ports: "2201:22"
      # - name: worker2
      #   expose: 22
      #   ports: "2202:22"
  roles:
    - role: provision_docker
      provision_docker_inventory: "{{inventory}}"
    - role: role-ansible_deps
    
  # tasks:
  #   - name: cluster group
  #     add_host:
  #       hostname: "{{item}}"
  #       groups: spark-ec2
  #     with_items:
  #       - master
  #       # - worker1
  #       # - worker2
  #     tags: provision_docker

#     - name: Group master
#       add_host:
#         hostname: "{{item}}"
#         groups: spark-ec2-master
#       with_items:
#         - master
#       tags: provision_docker
#
#     - name: Group workers
#       add_host:
#         hostname: "{{item}}"
#         groups: secondary
#       with_items:
#         - worker1
#         - worker2
#       tags: provision_docker
#
# - name: Test Install
#   hosts: primary:secondary
#   pre_tasks:
#      - name: "Build hosts file"
#        #lineinfile: dest=/etc/hosts regexp='.*{{inventory_hostname}}$' line="{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{inventory_hostname}}" state=present
#        shell: 'echo "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }} {{inventory_hostname}}" >> /etc/hosts'
#        when: hostvars[inventory_hostname].ansible_default_ipv4.address is defined
  #
  # tasks:
  #   - name: Test connection to instances.
  #     command: "echo hi"
  #
  #   - debug:
  #       msg: "Running on host {{inventory_hostname}}, {{ ansible_ssh_host }}"
